### ISSUE TITLE
I2s Stereo input slave mode example

### ISSUE THREAD

**Issue by LouisCARRIOU** [malacalypse/rp2040_i2s_example#4]
Hello,
I'm trying to use your nice i2s lib in slave mode. 
I'm using a WN8782 module to analyze right and left sound  but iI don't  find a working solution .
I also tried with a CS5343 but I  have the  same problem. 
Do you have a working example for i2s stereo input I'm slave mode ?
BR
Louis

**Comment by appliedsine** [comment]
I have this working in slave mode but the audio is really distorted, it feels like a clock issue to me but it's hard to tell with the scope I have.  

Re: your issue, Louis, all you have to do to run this in slave mode is call

 `i2s_program_start_slaved(pio0, &i2s_config_default, dma_i2s_in_handler, &i2s);`

instead of 

`i2s_program_start_synched(pio0, &i2s_config_default, dma_i2s_in_handler, &i2s);`

the default pin connections are as follows:

- i2s data out pin -> GPIO6 (out from pico)
- i2s data in pin -> GPIO7 (in to pico)
- i2s bit clock 'BCLK' -> GPIO8
- i2s frame clock LRCLK -> GPIO9
- master clock (SCK) out -> GPIO10 (freq is ~12.288 mHz)

I have verified that the above does in fact work, the codec I am using is my test codec, pcm5102A.  I get audio to come through but it is heavily distorted. If you get no audio, you may need to look at the codec to see if it is being initialized correctly. 

To the author of the code, I am working on a hobby project that I really want to incorporate this into, will pay $100 (+ another $100 if we get it running) for 1 hour of QA/help on this if you're interested.
